#!/usr/bin/env bash
# Regenerates vendor/sanitize-html.js: a single-file CommonJS bundle of
# sanitize-html and its dependencies. Nothing is left in node_modules;
# everything is built in a temp dir.
#
# Usage: scripts/vendor-sanitize-html.sh [sanitize-html-version]
set -euo pipefail

SANITIZE_HTML_VERSION="${1:-2.17.7}"
ESBUILD_VERSION="0.24.2"

here="$(cd "$(dirname "$0")/.." && pwd)"
out="$here/vendor/sanitize-html.js"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

cd "$tmp"
echo '{"private":true}' > package.json
npm install --no-audit --no-fund --loglevel=error \
  "sanitize-html@${SANITIZE_HTML_VERSION}" "esbuild@${ESBUILD_VERSION}"
echo "module.exports = require('sanitize-html');" > entry.js
./node_modules/.bin/esbuild entry.js --bundle --platform=node --format=cjs \
  --target=node22 --legal-comments=eof --outfile=bundle.js --log-level=warning

# Legal comments for dependencies that carry none inline.
{
  cat <<HDR
/*!
 * vendor/sanitize-html.js
 *
 * Single-file CommonJS bundle of sanitize-html ${SANITIZE_HTML_VERSION} and its
 * dependencies (MIT and other licences; see the licence block at the end).
 * Generated by tools/publish/scripts/vendor-sanitize-html.sh using:
 *   esbuild@${ESBUILD_VERSION} entry.js --bundle --platform=node --format=cjs \\
 *     --target=node22 --legal-comments=eof
 * where entry.js is: module.exports = require('sanitize-html');
 * DO NOT EDIT BY HAND. Regenerate with the script above.
 */
HDR
  cat bundle.js
  echo
  echo '/*!'
  echo ' * Licence texts of bundled packages (appended by the vendor script).'
  echo ' */'
  echo '/*!'
  bundled="$(grep -o 'node_modules/[^"]*' bundle.js | sed -E 's#^node_modules/((@[^/]+/)?[^/]+)/.*#\1#' | sort -u)"
  for p in $bundled; do
    f="$(ls node_modules/$p/LICENSE* node_modules/$p/LICENCE* node_modules/$p/license* 2>/dev/null | head -1 || true)"
    ver="$(node -p "require('./node_modules/$p/package.json').version")"
    lic="$(node -p "const l=require('./node_modules/$p/package.json').license; typeof l==='string'?l:JSON.stringify(l)")"
    echo " * ---- $p@$ver ($lic) ----"
    if [ -n "$f" ]; then sed 's#\*/#* /#g; s#^# * #' "$f"; else echo " * (no licence file shipped; see package.json licence field)"; fi
    echo " *"
  done
  echo ' */'
} > "$out"
echo "wrote $out ($(wc -c < "$out") bytes)"
